import type { ApiEndpoint } from '../types/api';
import { zuoraEnvironments } from './environments';

export const postAccountEndpoint: ApiEndpoint = {
  id: 'post-account',
  name: 'Create Account',
  description: 'Creates a customer account with billing and payment information',
  method: 'POST',
  path: '/v1/accounts',
  baseUrl: 'https://rest.zuora.com',
  environments: zuoraEnvironments,
  requiresAuth: true,
  authType: 'bearer',
  headers: {
    'Content-Type': 'application/json',
  },
  bodyFields: [
    // ===== REQUIRED FIELDS =====
    {
      name: 'name',
      label: 'Account Name',
      type: 'string',
      required: true,
      description: 'Account name, up to 255 characters',
      placeholder: 'e.g., Acme Corporation',
      maxLength: 255,
    },
    {
      name: 'currency',
      label: 'Currency',
      type: 'string',
      required: true,
      description: 'A currency as defined in Billing Settings',
      placeholder: 'USD',
      enum: ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', 'BRL', 'MXN'],
    },
    {
      name: 'billCycleDay',
      label: 'Bill Cycle Day',
      type: 'number',
      required: true,
      description: "The account's bill cycle day (BCD), when bill runs generate invoices (1-31, or 0 for auto-set)",
      placeholder: '1',
      defaultValue: 1,
    },
    {
      name: 'billToContact',
      label: 'Bill To Contact',
      type: 'object',
      required: true,
      description: 'Billing contact information',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'workEmail',
          label: 'Email',
          type: 'email',
          required: true,
          placeholder: 'john.doe@example.com',
          maxLength: 80,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'address2',
          label: 'Address Line 2',
          type: 'string',
          required: false,
          placeholder: 'Suite 100',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
        {
          name: 'workPhone',
          label: 'Work Phone',
          type: 'string',
          required: false,
          placeholder: '+1 (555) 123-4567',
          maxLength: 40,
        },
        {
          name: 'mobilePhone',
          label: 'Mobile Phone',
          type: 'string',
          required: false,
          placeholder: '+1 (555) 987-6543',
          maxLength: 40,
        },
      ],
    },

    // ===== ACCOUNT SETTINGS =====
    {
      name: 'accountNumber',
      label: 'Account Number',
      type: 'string',
      required: false,
      description: 'Unique account identifier (auto-generated if not provided)',
      placeholder: 'A00000001',
      maxLength: 70,
      section: 'Account Settings',
    },
    {
      name: 'batch',
      label: 'Batch',
      type: 'string',
      required: false,
      description: 'The alias name given to a batch (up to 50 characters)',
      placeholder: 'Batch1',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'crmId',
      label: 'CRM Account ID',
      type: 'string',
      required: false,
      description: 'CRM account ID for the account',
      placeholder: 'CRM-12345',
      maxLength: 100,
      section: 'Account Settings',
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      required: false,
      description: 'Additional notes about the account',
      placeholder: 'Enter any additional information...',
      maxLength: 65535,
      section: 'Account Settings',
    },
    {
      name: 'salesRep',
      label: 'Sales Representative',
      type: 'string',
      required: false,
      description: "Name of the account's sales representative",
      placeholder: 'John Smith',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'customerServiceRepName',
      label: 'Customer Service Rep',
      type: 'string',
      required: false,
      description: "Name of the account's customer service representative",
      placeholder: 'Jane Doe',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'purchaseOrderNumber',
      label: 'Purchase Order Number',
      type: 'string',
      required: false,
      description: 'Purchase order number provided by customer',
      placeholder: 'PO-2024-001',
      section: 'Account Settings',
    },

    // ===== PAYMENT SETTINGS =====
    {
      name: 'autoPay',
      label: 'Auto Pay',
      type: 'boolean',
      required: false,
      description: 'Whether future payments are automatically billed when due',
      defaultValue: false,
      section: 'Payment Settings',
    },
    {
      name: 'paymentTerm',
      label: 'Payment Terms',
      type: 'string',
      required: false,
      description: 'Payment terms for this account',
      enum: ['Due Upon Receipt', 'Net 30', 'Net 60', 'Net 90'],
      section: 'Payment Settings',
    },
    {
      name: 'paymentGateway',
      label: 'Payment Gateway',
      type: 'string',
      required: false,
      description: 'Name of the payment gateway instance',
      placeholder: 'Default Gateway',
      section: 'Payment Settings',
    },

    // ===== INVOICE SETTINGS =====
    {
      name: 'invoiceDeliveryPrefsEmail',
      label: 'Email Invoices',
      type: 'boolean',
      required: false,
      description: 'Whether the customer wants to receive invoices through email',
      defaultValue: false,
      section: 'Invoice & Document Settings',
    },
    {
      name: 'invoiceDeliveryPrefsPrint',
      label: 'Print Invoices',
      type: 'boolean',
      required: false,
      description: 'Whether the customer wants to receive printed invoices',
      defaultValue: false,
      section: 'Invoice & Document Settings',
    },
    {
      name: 'invoiceTemplateId',
      label: 'Invoice Template ID',
      type: 'string',
      required: false,
      description: 'Invoice template ID or number configured in Billing Settings',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'creditMemoTemplateId',
      label: 'Credit Memo Template ID',
      type: 'string',
      required: false,
      description: 'Unique ID of the credit memo template',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'debitMemoTemplateId',
      label: 'Debit Memo Template ID',
      type: 'string',
      required: false,
      description: 'Unique ID of the debit memo template',
      placeholder: '2c92c08d62470a8501626b19d24f19e2',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'summaryStatementTemplateId',
      label: 'Summary Statement Template ID',
      type: 'string',
      required: false,
      description: 'Template ID used to produce summary statement PDFs',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'documentDate',
      label: 'Document Date',
      type: 'date',
      required: false,
      description: 'The date of the billing document (invoice, credit memo, debit memo)',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'creditMemoReasonCode',
      label: 'Credit Memo Reason Code',
      type: 'string',
      required: false,
      description: 'Code identifying the reason for credit memo transactions',
      placeholder: 'Standard Adjustment',
      section: 'Invoice & Document Settings',
    },

    // ===== SOLD TO CONTACT =====
    {
      name: 'soldToSameAsBillTo',
      label: 'Sold-To Same as Bill-To',
      type: 'boolean',
      required: false,
      description: 'Whether the sold-to contact and bill-to contact are the same',
      defaultValue: false,
      section: 'Sold-To Contact',
    },
    {
      name: 'soldToContact',
      label: 'Sold To Contact',
      type: 'object',
      required: false,
      description: 'Sold-to contact information (uses Bill-To if not specified)',
      section: 'Sold-To Contact',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'workEmail',
          label: 'Email',
          type: 'email',
          required: false,
          placeholder: 'john.doe@example.com',
          maxLength: 80,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
      ],
    },

    // ===== SHIP TO CONTACT =====
    {
      name: 'shipToSameAsBillTo',
      label: 'Ship-To Same as Bill-To',
      type: 'boolean',
      required: false,
      description: 'Whether the ship-to contact and bill-to contact are the same',
      defaultValue: false,
      section: 'Ship-To Contact',
    },
    {
      name: 'shipToContact',
      label: 'Ship To Contact',
      type: 'object',
      required: false,
      description: 'Shipping contact information',
      section: 'Ship-To Contact',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
      ],
    },

    // ===== CREDIT & INVOICE SETTLEMENT =====
    {
      name: 'applyCredit',
      label: 'Auto Apply Credit',
      type: 'boolean',
      required: false,
      description: 'Whether to automatically apply credit memos or unapplied payments to invoices',
      defaultValue: false,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'applyCreditBalance',
      label: 'Apply Credit Balance',
      type: 'boolean',
      required: false,
      description: 'Applies credit balance to an invoice',
      defaultValue: false,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'collect',
      label: 'Collect Payment',
      type: 'boolean',
      required: false,
      description: 'Collects an automatic payment for a subscription',
      defaultValue: true,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'runBilling',
      label: 'Run Billing',
      type: 'boolean',
      required: false,
      description: 'Creates an invoice for a subscription',
      defaultValue: true,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'targetDate',
      label: 'Target Date',
      type: 'date',
      required: false,
      description: 'Date through which to calculate charges',
      section: 'Credit & Settlement Settings',
    },

    // ===== COMMUNICATION SETTINGS =====
    {
      name: 'communicationProfileId',
      label: 'Communication Profile ID',
      type: 'string',
      required: false,
      description: 'ID of the communication profile linked to this account',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Communication Settings',
    },
    {
      name: 'profileNumber',
      label: 'Profile Number',
      type: 'string',
      required: false,
      description: 'Number of the communication profile linked to this account',
      placeholder: 'CP-001',
      section: 'Communication Settings',
    },
    {
      name: 'additionalEmailAddresses',
      label: 'Additional Email Addresses',
      type: 'string',
      required: false,
      description: 'Comma-separated list of additional email addresses for notifications',
      placeholder: 'email1@example.com, email2@example.com',
      section: 'Communication Settings',
    },

    // ===== ADVANCED SETTINGS =====
    {
      name: 'sequenceSetId',
      label: 'Sequence Set ID',
      type: 'string',
      required: false,
      description: 'ID or number of the billing document sequence set',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Advanced Settings',
    },
    {
      name: 'parentId',
      label: 'Parent Account ID',
      type: 'string',
      required: false,
      description: 'Identifier of the parent customer account (requires Customer Hierarchy)',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      maxLength: 32,
      section: 'Advanced Settings',
    },
    {
      name: 'organizationLabel',
      label: 'Organization Label',
      type: 'string',
      required: false,
      description: 'Name of the organization that the account belongs to (Multi-Org feature)',
      placeholder: 'Organization Name',
      section: 'Advanced Settings',
    },
    {
      name: 'partnerAccount',
      label: 'Partner Account',
      type: 'boolean',
      required: false,
      description: 'Whether the customer account is a partner, distributor, or reseller',
      defaultValue: false,
      section: 'Advanced Settings',
    },
    {
      name: 'gatewayRoutingEligible',
      label: 'Gateway Routing Eligible',
      type: 'boolean',
      required: false,
      description: 'Include account in gateway routing for controlled adoption',
      defaultValue: false,
      section: 'Advanced Settings',
    },
    {
      name: 'tagging',
      label: 'Tags',
      type: 'string',
      required: false,
      description: 'Tags for categorizing the account',
      placeholder: 'enterprise, premium',
      section: 'Advanced Settings',
    },
  ],
  exampleRequest: {
    name: 'Acme Corporation',
    currency: 'USD',
    billCycleDay: 1,
    autoPay: false,
    billToContact: {
      firstName: 'John',
      lastName: 'Doe',
      workEmail: 'john.doe@acme.com',
      address1: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      country: 'United States',
    },
  },
  exampleResponse: {
    success: true,
    accountId: '8ad0894c8b7c8e9c018b7d0c2e3f1234',
    accountNumber: 'A00000001',
  },
};
