import type { ApiEndpoint } from '../types/api';
import { zuoraEnvironments } from './environments';

export const postAccountEndpoint: ApiEndpoint = {
  id: 'post-account',
  name: 'Create Account',
  description: 'Creates a customer account with billing and payment information',
  method: 'POST',
  path: '/v1/accounts',
  baseUrl: 'https://rest.zuora.com',
  environments: zuoraEnvironments,
  requiresAuth: true,
  authType: 'bearer',
  headers: {
    'Content-Type': 'application/json',
    'Zuora-Track-Id': '',
    'Zuora-Entity-Ids': '',
    'Zuora-Org-Ids': '',
    'Zuora-Version': '',
  },
  bodyFields: [
    // ===== REQUIRED FIELDS =====
    {
      name: 'name',
      label: 'Account Name',
      type: 'string',
      required: true,
      description: 'Account name, up to 255 characters',
      placeholder: 'e.g., Acme Corporation',
      maxLength: 255,
    },
    {
      name: 'currency',
      label: 'Currency',
      type: 'string',
      required: true,
      description: 'A currency as defined in Billing Settings',
      placeholder: 'USD',
      enum: ['USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', 'BRL', 'MXN'],
    },
    {
      name: 'billCycleDay',
      label: 'Bill Cycle Day',
      type: 'number',
      required: true,
      description: "The account's bill cycle day (BCD), when bill runs generate invoices (1-31, or 0 for auto-set)",
      placeholder: '1',
    },
    {
      name: 'billToContact',
      label: 'Bill To Contact',
      type: 'object',
      required: true,
      description: 'Billing contact information',
      section: 'Bill-To Contact',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'workEmail',
          label: 'Email',
          type: 'email',
          required: true,
          placeholder: 'john.doe@example.com',
          maxLength: 80,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'address2',
          label: 'Address Line 2',
          type: 'string',
          required: false,
          placeholder: 'Suite 100',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
        {
          name: 'workPhone',
          label: 'Work Phone',
          type: 'string',
          required: false,
          placeholder: '+1 (555) 123-4567',
          maxLength: 40,
        },
        {
          name: 'mobilePhone',
          label: 'Mobile Phone',
          type: 'string',
          required: false,
          placeholder: '+1 (555) 987-6543',
          maxLength: 40,
        },
      ],
    },

    // ===== ACCOUNT SETTINGS =====
    {
      name: 'accountNumber',
      label: 'Account Number',
      type: 'string',
      required: false,
      description: 'Unique account identifier (auto-generated if not provided)',
      placeholder: 'A00000001',
      maxLength: 70,
      section: 'Account Settings',
    },
    {
      name: 'batch',
      label: 'Batch',
      type: 'string',
      required: false,
      description: 'The alias name given to a batch (up to 50 characters)',
      placeholder: 'Batch1',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'crmId',
      label: 'CRM Account ID',
      type: 'string',
      required: false,
      description: 'CRM account ID for the account',
      placeholder: 'CRM-12345',
      maxLength: 100,
      section: 'Account Settings',
    },
    {
      name: 'notes',
      label: 'Notes',
      type: 'textarea',
      required: false,
      description: 'Additional notes about the account',
      placeholder: 'Enter any additional information...',
      maxLength: 65535,
      section: 'Account Settings',
    },
    {
      name: 'salesRep',
      label: 'Sales Representative',
      type: 'string',
      required: false,
      description: "Name of the account's sales representative",
      placeholder: 'John Smith',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'customerServiceRepName',
      label: 'Customer Service Rep',
      type: 'string',
      required: false,
      description: "Name of the account's customer service representative",
      placeholder: 'Jane Doe',
      maxLength: 50,
      section: 'Account Settings',
    },
    {
      name: 'purchaseOrderNumber',
      label: 'Purchase Order Number',
      type: 'string',
      required: false,
      description: 'Purchase order number provided by customer',
      placeholder: 'PO-2024-001',
      section: 'Account Settings',
    },

    // ===== PAYMENT SETTINGS =====
    {
      name: 'autoPay',
      label: 'Auto Pay',
      type: 'boolean',
      required: false,
      description: 'Whether future payments are automatically billed when due',
      defaultValue: false,
      section: 'Payment Settings',
    },
    {
      name: 'paymentTerm',
      label: 'Payment Terms',
      type: 'string',
      required: false,
      description: 'Payment terms for this account',
      enum: ['Due Upon Receipt', 'Net 30', 'Net 60', 'Net 90'],
      section: 'Payment Settings',
    },
    {
      name: 'paymentGateway',
      label: 'Payment Gateway',
      type: 'string',
      required: false,
      description: 'Name of the payment gateway instance',
      placeholder: 'Default Gateway',
      section: 'Payment Settings',
    },
    {
      name: 'hpmCreditCardPaymentMethodId',
      label: 'HPM Credit Card Payment Method ID',
      type: 'string',
      required: false,
      description: 'The ID of the payment method associated with this account',
      section: 'Payment Settings',
    },
    {
      name: 'paymentMethod',
      label: 'Payment Method',
      type: 'object',
      required: false,
      description: 'Payment method information',
      section: 'Payment Settings',
      fields: [
        {
          name: 'type',
          label: 'Type',
          type: 'string',
          required: false,
          enum: [
            'CreditCard',
            'CreditCardReferenceTransaction',
            'ACH',
            'SEPA',
            'Betalingsservice',
            'Autogiro',
            'Bacs',
            'Becs',
            'Becsnz',
            'PAD',
            'PayPalCP',
            'PayPalEC',
            'PayPalNativeEC',
            'PayPalAdaptive',
            'AdyenApplePay',
            'AdyenGooglePay',
            'GooglePay',
            'AmazonPay',
          ],
        },
        {
          name: 'cardHolderInfo',
          label: 'Card Holder Info',
          type: 'object',
          required: false,
          fields: [
            {
              name: 'cardHolderName',
              label: 'Card Holder Name',
              type: 'string',
              required: false,
              placeholder: 'John J Smith',
              maxLength: 50,
            },
            {
              name: 'addressLine1',
              label: 'Address Line 1',
              type: 'string',
              required: false,
              maxLength: 255,
            },
            {
              name: 'addressLine2',
              label: 'Address Line 2',
              type: 'string',
              required: false,
              maxLength: 255,
            },
            {
              name: 'city',
              label: 'City',
              type: 'string',
              required: false,
              maxLength: 40,
            },
            {
              name: 'state',
              label: 'State',
              type: 'string',
              required: false,
              maxLength: 40,
            },
            {
              name: 'zipCode',
              label: 'Zip Code',
              type: 'string',
              required: false,
              maxLength: 20,
            },
            {
              name: 'country',
              label: 'Country',
              type: 'string',
              required: false,
              maxLength: 40,
            },
            {
              name: 'email',
              label: 'Email',
              type: 'email',
              required: false,
              maxLength: 80,
            },
            {
              name: 'phone',
              label: 'Phone',
              type: 'string',
              required: false,
              maxLength: 40,
            },
          ],
        },
        {
          name: 'cardType',
          label: 'Card Type',
          type: 'string',
          required: false,
          enum: ['Visa', 'MasterCard', 'AmericanExpress', 'Discover', 'JCB', 'Diners'],
        },
        {
          name: 'cardNumber',
          label: 'Card Number',
          type: 'string',
          required: false,
          placeholder: 'xxxxxxxxxxxxxxxx',
        },
        {
          name: 'expirationMonth',
          label: 'Exp Month',
          type: 'number',
          required: false,
        },
        {
          name: 'expirationYear',
          label: 'Exp Year',
          type: 'number',
          required: false,
        },
        {
          name: 'securityCode',
          label: 'Security Code',
          type: 'string',
          required: false,
          placeholder: 'CVV',
        },
      ],
    },

    // ===== INVOICE SETTINGS =====
    {
      name: 'invoiceDeliveryPrefsEmail',
      label: 'Email Invoices',
      type: 'boolean',
      required: false,
      description: 'Whether the customer wants to receive invoices through email',
      defaultValue: false,
      section: 'Invoice & Document Settings',
    },
    {
      name: 'invoiceDeliveryPrefsPrint',
      label: 'Print Invoices',
      type: 'boolean',
      required: false,
      description: 'Whether the customer wants to receive printed invoices',
      defaultValue: false,
      section: 'Invoice & Document Settings',
    },
    {
      name: 'invoiceTemplateId',
      label: 'Invoice Template ID',
      type: 'string',
      required: false,
      description: 'Invoice template ID or number configured in Billing Settings',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'creditMemoTemplateId',
      label: 'Credit Memo Template ID',
      type: 'string',
      required: false,
      description: 'Unique ID of the credit memo template',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'debitMemoTemplateId',
      label: 'Debit Memo Template ID',
      type: 'string',
      required: false,
      description: 'Unique ID of the debit memo template',
      placeholder: '2c92c08d62470a8501626b19d24f19e2',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'summaryStatementTemplateId',
      label: 'Summary Statement Template ID',
      type: 'string',
      required: false,
      description: 'Template ID used to produce summary statement PDFs',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'documentDate',
      label: 'Document Date',
      type: 'date',
      required: false,
      description: 'The date of the billing document (invoice, credit memo, debit memo)',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'creditMemoReasonCode',
      label: 'Credit Memo Reason Code',
      type: 'string',
      required: false,
      description: 'Code identifying the reason for credit memo transactions',
      placeholder: 'Standard Adjustment',
      section: 'Invoice & Document Settings',
    },
    {
      name: 'einvoiceProfile',
      label: 'E-Invoice Profile',
      type: 'object',
      required: false,
      description: 'Container for e-invoicing profile information',
      section: 'Invoice & Document Settings',
      fields: [
         {
             name: 'enabled',
             label: 'Enabled',
             type: 'boolean',
             required: false,
         },
         {
             name: 'businessCategory',
             label: 'Business Category',
             type: 'string',
             required: false,
             enum: ['B2B', 'B2C', 'B2G'],
         }
      ]
    },

    // ===== SOLD TO CONTACT =====
    {
      name: 'soldToSameAsBillTo',
      label: 'Sold-To Same as Bill-To',
      type: 'boolean',
      required: false,
      description: 'Whether the sold-to contact and bill-to contact are the same',
      defaultValue: false,
      section: 'Sold-To Contact',
    },
    {
      name: 'soldToContact',
      label: 'Sold To Contact',
      type: 'object',
      required: false,
      description: 'Sold-to contact information (uses Bill-To if not specified)',
      section: 'Sold-To Contact',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'workEmail',
          label: 'Email',
          type: 'email',
          required: false,
          placeholder: 'john.doe@example.com',
          maxLength: 80,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
      ],
    },

    // ===== SHIP TO CONTACT =====
    {
      name: 'shipToSameAsBillTo',
      label: 'Ship-To Same as Bill-To',
      type: 'boolean',
      required: false,
      description: 'Whether the ship-to contact and bill-to contact are the same',
      defaultValue: false,
      section: 'Ship-To Contact',
    },
    {
      name: 'shipToContact',
      label: 'Ship To Contact',
      type: 'object',
      required: false,
      description: 'Shipping contact information',
      section: 'Ship-To Contact',
      fields: [
        {
          name: 'firstName',
          label: 'First Name',
          type: 'string',
          required: true,
          placeholder: 'John',
          maxLength: 100,
        },
        {
          name: 'lastName',
          label: 'Last Name',
          type: 'string',
          required: true,
          placeholder: 'Doe',
          maxLength: 100,
        },
        {
          name: 'address1',
          label: 'Address Line 1',
          type: 'string',
          required: false,
          placeholder: '123 Main St',
          maxLength: 255,
        },
        {
          name: 'city',
          label: 'City',
          type: 'string',
          required: false,
          placeholder: 'San Francisco',
          maxLength: 100,
        },
        {
          name: 'state',
          label: 'State/Province',
          type: 'string',
          required: false,
          placeholder: 'CA',
          maxLength: 100,
        },
        {
          name: 'zipCode',
          label: 'Zip/Postal Code',
          type: 'string',
          required: false,
          placeholder: '94105',
          maxLength: 20,
        },
        {
          name: 'country',
          label: 'Country',
          type: 'string',
          required: false,
          placeholder: 'United States',
          maxLength: 64,
        },
      ],
    },

    // ===== CREDIT & INVOICE SETTLEMENT =====
    {
      name: 'applicationOrder',
      label: 'Application Order',
      type: 'string',
      required: false,
      description: 'The priority order to apply credit memos and/or unapplied payments to an invoice',
      enum: ['CreditMemo', 'UnappliedPayment'],
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'applyCredit',
      label: 'Auto Apply Credit',
      type: 'boolean',
      required: false,
      description: 'Whether to automatically apply credit memos or unapplied payments to invoices',
      defaultValue: false,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'applyCreditBalance',
      label: 'Apply Credit Balance',
      type: 'boolean',
      required: false,
      description: 'Applies credit balance to an invoice',
      defaultValue: false,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'collect',
      label: 'Collect Payment',
      type: 'boolean',
      required: false,
      description: 'Collects an automatic payment for a subscription',
      defaultValue: true,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'runBilling',
      label: 'Run Billing',
      type: 'boolean',
      required: false,
      description: 'Creates an invoice for a subscription',
      defaultValue: true,
      section: 'Credit & Settlement Settings',
    },
    {
      name: 'targetDate',
      label: 'Target Date',
      type: 'date',
      required: false,
      description: 'Date through which to calculate charges',
      section: 'Credit & Settlement Settings',
    },

    // ===== TAX SETTINGS =====
    {
        name: 'taxInfo',
        label: 'Tax Information',
        type: 'object',
        required: false,
        section: 'Tax Settings',
        fields: [
            {
                name: 'VATId',
                label: 'VAT ID',
                type: 'string',
                required: false,
                description: 'EU Value Added Tax ID',
            },
            {
                name: 'companyCode',
                label: 'Company Code',
                type: 'string',
                required: false,
                description: 'Unique code that identifies a company account in Avalara',
            },
            {
                name: 'exemptCertificateId',
                label: 'Exempt Certificate ID',
                type: 'string',
                required: false,
                description: 'ID of the customer tax exemption certificate',
            },
            {
                name: 'exemptCertificateType',
                label: 'Exempt Certificate Type',
                type: 'string',
                required: false,
                description: 'Type of tax exemption certificate that the customer holds',
            },
            {
                name: 'exemptDescription',
                label: 'Exempt Description',
                type: 'string',
                required: false,
                description: 'Description of the tax exemption certificate',
            },
            {
                name: 'exemptEffectiveDate',
                label: 'Exempt Effective Date',
                type: 'date',
                required: false,
                description: 'Date when the customer tax exemption starts (yyyy-mm-dd)',
            },
            {
                name: 'exemptExpirationDate',
                label: 'Exempt Expiration Date',
                type: 'date',
                required: false,
                description: 'Date when the customer tax exemption expires (yyyy-mm-dd)',
            },
            {
                name: 'exemptIssuingJurisdiction',
                label: 'Exempt Issuing Jurisdiction',
                type: 'string',
                required: false,
                description: 'Jurisdiction in which the customer tax exemption certificate was issued',
            },
            {
                name: 'exemptStatus',
                label: 'Exempt Status',
                type: 'string',
                required: false,
                description: 'Status of the account tax exemption',
                enum: ['Yes', 'No', 'pendingVerification'],
            },
             {
                name: 'exemptEntityUseCode',
                label: 'Exempt Entity Use Code',
                type: 'string',
                required: false,
                description: 'A unique entity use code to apply exemptions in Avalara AvaTax',
            }
        ]
    },

    // ===== SUBSCRIPTION SETTINGS =====
    {
        name: 'subscription',
        label: 'Initial Subscription',
        type: 'object',
        required: false,
        description: 'Information to create a subscription for the new account',
        section: 'Subscription Settings',
        fields: [
            {
                name: 'termType',
                label: 'Term Type',
                type: 'string',
                required: false,
                enum: ['TERMED', 'EVERGREEN'],
            },
            {
                name: 'contractEffectiveDate',
                label: 'Contract Effective Date',
                type: 'date',
                required: false,
            },
            {
                name: 'subscribeToRatePlans',
                label: 'Rate Plans',
                type: 'object',
                required: false,
                // Simplified for now, this can be complex
                fields: [
                    {
                        name: 'productRatePlanId',
                        label: 'Product Rate Plan ID',
                        type: 'string',
                        required: false,
                    }
                ]
            }
        ]
    },

    // ===== COMMUNICATION SETTINGS =====
    {
      name: 'communicationProfileId',
      label: 'Communication Profile ID',
      type: 'string',
      required: false,
      description: 'ID of the communication profile linked to this account',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Communication Settings',
    },
    {
      name: 'profileNumber',
      label: 'Profile Number',
      type: 'string',
      required: false,
      description: 'Number of the communication profile linked to this account',
      placeholder: 'CP-001',
      section: 'Communication Settings',
    },
    {
      name: 'additionalEmailAddresses',
      label: 'Additional Email Addresses',
      type: 'string',
      required: false,
      description: 'Comma-separated list of additional email addresses for notifications',
      placeholder: 'email1@example.com, email2@example.com',
      section: 'Communication Settings',
    },

    // ===== INTEGRATIONS (NetSuite) =====
    {
      name: 'Class__NS',
      label: 'Class (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'CustomerType__NS',
      label: 'Customer Type (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'Department__NS',
      label: 'Department (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'IntegrationId__NS',
      label: 'Integration ID (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'IntegrationStatus__NS',
      label: 'Integration Status (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'Location__NS',
      label: 'Location (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'Subsidiary__NS',
      label: 'Subsidiary (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'SyncDate__NS',
      label: 'Sync Date (NetSuite)',
      type: 'string',
      required: false,
      section: 'Integrations',
    },
    {
      name: 'SynctoNetSuite__NS',
      label: 'Sync to NetSuite',
      type: 'string',
      required: false,
      enum: ['Yes', 'No'],
      section: 'Integrations',
    },

    // ===== ADVANCED SETTINGS =====
    {
      name: 'sequenceSetId',
      label: 'Sequence Set ID',
      type: 'string',
      required: false,
      description: 'ID or number of the billing document sequence set',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      section: 'Advanced Settings',
    },
    {
      name: 'parentId',
      label: 'Parent Account ID',
      type: 'string',
      required: false,
      description: 'Identifier of the parent customer account (requires Customer Hierarchy)',
      placeholder: '2c92c08a6246fdf101626b1b3fe0144b',
      maxLength: 32,
      section: 'Advanced Settings',
    },
    {
      name: 'organizationLabel',
      label: 'Organization Label',
      type: 'string',
      required: false,
      description: 'Name of the organization that the account belongs to (Multi-Org feature)',
      placeholder: 'Organization Name',
      section: 'Advanced Settings',
    },
    {
      name: 'partnerAccount',
      label: 'Partner Account',
      type: 'boolean',
      required: false,
      description: 'Whether the customer account is a partner, distributor, or reseller',
      defaultValue: false,
      section: 'Advanced Settings',
    },
    {
      name: 'gatewayRoutingEligible',
      label: 'Gateway Routing Eligible',
      type: 'boolean',
      required: false,
      description: 'Include account in gateway routing for controlled adoption',
      defaultValue: false,
      section: 'Advanced Settings',
    },
    {
      name: 'tagging',
      label: 'Tags',
      type: 'string',
      required: false,
      description: 'Tags for categorizing the account',
      placeholder: 'enterprise, premium',
      section: 'Advanced Settings',
    },
  ],
  exampleRequest: {
    name: 'Acme Corporation',
    currency: 'USD',
    billCycleDay: 1,
    autoPay: false,
    billToContact: {
      firstName: 'John',
      lastName: 'Doe',
      workEmail: 'john.doe@acme.com',
      address1: '123 Main Street',
      city: 'San Francisco',
      state: 'CA',
      zipCode: '94105',
      country: 'United States',
    },
  },
  exampleResponse: {
    success: true,
    accountId: '8ad0894c8b7c8e9c018b7d0c2e3f1234',
    accountNumber: 'A00000001',
  },
};
