import type { ApiEndpoint } from '../types/api';

// Revenue base URL is stored in localStorage as 'zuora_revenue_host'
// and injected at runtime by apiExecutor.ts for product==='revenue' endpoints.
const REVENUE_BASE = 'https://yourHost';

export const revenueEndpoints: ApiEndpoint[] = [
  // ── Adapter ───────────────────────────────────────────────────────────────
  {
    id: 'revenue-get-field-mapping',
    name: 'Get field mapping',
    description: 'Returns the field mapping information for the specified upload template.',
    method: 'GET',
    path: '/api/integration/v1/upload/mapping',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    queryParams: [
      {
        name: 'templatename',
        label: 'Template Name',
        type: 'string',
        required: false,
        description: 'Name of the upload template that contains the field mapping information.',
      },
    ],
  },

  // ── BI Views v1 ───────────────────────────────────────────────────────────
  {
    id: 'revenue-get-bi-views',
    name: 'Get BI Views',
    description: 'Returns BI view data for the specified view name and date range.',
    method: 'GET',
    path: '/api/integration/v1/biviews/{view_name}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'view_name',
        label: 'View Name',
        type: 'string',
        required: true,
        description: 'Name of the BI view.',
      },
    ],
    queryParams: [
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'number',
        required: true,
        description: 'The ID of the Zuora Revenue application user.',
      },
      {
        name: 'fromDate',
        label: 'From Date',
        type: 'string',
        required: true,
        description: 'The date from which the data query begins.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'toDate',
        label: 'To Date',
        type: 'string',
        required: true,
        description: 'The date on which the data query ends.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'pagenum',
        label: 'Page Number',
        type: 'number',
        required: true,
        description: 'The number of page to download.',
      },
      {
        name: 'pagesize',
        label: 'Page Size',
        type: 'number',
        required: false,
        description: 'The number of records to be downloaded per request. Default is 1000, maximum is 10000.',
      },
      {
        name: 'count',
        label: 'Count Only',
        type: 'boolean',
        required: false,
        description: 'Set to true to get the row count of the BI view for the specified time period.',
      },
    ],
  },
  {
    id: 'revenue-get-bi-view-data-selected-fields',
    name: 'Get BI View data for selected fields',
    description: 'Returns BI view data for selected fields within the specified view name and date range.',
    method: 'POST',
    path: '/api/integration/v1/biviews/{view_name}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'view_name',
        label: 'View Name (tmpl_name)',
        type: 'string',
        required: true,
        description: 'Name of the BI view.',
      },
    ],
    queryParams: [
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'number',
        required: true,
        description: 'The ID of the Zuora Revenue application user.',
      },
      {
        name: 'fromDate',
        label: 'From Date',
        type: 'string',
        required: true,
        description: 'The date from which the data query begins.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'toDate',
        label: 'To Date',
        type: 'string',
        required: true,
        description: 'The date on which the data query ends.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'pagenum',
        label: 'Page Number',
        type: 'number',
        required: true,
        description: 'The number of page to download.',
      },
      {
        name: 'count',
        label: 'Count Only',
        type: 'boolean',
        required: false,
        description: 'Set to true to get the row count of the BI view for the specified time period.',
      },
    ],
  },

  // ── BI Views v2 ───────────────────────────────────────────────────────────
  {
    id: 'revenue-get-all-task-status',
    name: 'Get all task status',
    description: 'Returns the status of all active BI view tasks.',
    method: 'GET',
    path: '/api/integration/v2/biviews-status',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
  },
  {
    id: 'revenue-cancel-task',
    name: 'Cancel task',
    description: 'Cancels the specified active BI view task.',
    method: 'DELETE',
    path: '/api/integration/v2/biviews-status/{task_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'task_id',
        label: 'Task ID',
        type: 'string',
        required: true,
        description: 'The continuation token associated with the task to be canceled.',
      },
    ],
  },
  {
    id: 'revenue-get-active-task-details',
    name: 'Get active task details',
    description: 'Returns the details of an active BI view task.',
    method: 'GET',
    path: '/api/integration/v2/biviews-status/{task_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'task_id',
        label: 'Task ID',
        type: 'string',
        required: true,
        description: 'The continuation token that was returned in the initial request.',
      },
    ],
  },
  {
    id: 'revenue-get-row-count',
    name: 'Get row count',
    description: 'Returns the row count for the specified BI view and date range.',
    method: 'GET',
    path: '/api/integration/v2/biviews/count/{tmpl_name}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'tmpl_name',
        label: 'Template Name',
        type: 'string',
        required: true,
        description: 'Name of the BI view.',
      },
    ],
    queryParams: [
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'number',
        required: true,
        description: 'The ID of the Zuora Revenue application user.',
      },
      {
        name: 'fromDate',
        label: 'From Date',
        type: 'string',
        required: false,
        description: 'The date from which the data query begins.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'toDate',
        label: 'To Date',
        type: 'string',
        required: false,
        description: 'The date on which the data query ends.',
        placeholder: 'YYYY-MM-DD',
      },
    ],
  },
  {
    id: 'revenue-download-bi-view',
    name: 'Download BI view',
    description: 'Downloads the BI view data for the specified view name and date range.',
    method: 'GET',
    path: '/api/integration/v2/biviews/{view_name}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'view_name',
        label: 'View Name',
        type: 'string',
        required: true,
        description: 'Name of the BI view.',
      },
    ],
    queryParams: [
      {
        name: 'clientId',
        label: 'Client ID',
        type: 'number',
        required: true,
        description: 'The ID of the Zuora Revenue application user.',
      },
      {
        name: 'fromDate',
        label: 'From Date',
        type: 'string',
        required: true,
        description: 'The date from which the data query begins.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'toDate',
        label: 'To Date',
        type: 'string',
        required: true,
        description: 'The date on which the data query ends.',
        placeholder: 'YYYY-MM-DD',
      },
      {
        name: 'pagenum',
        label: 'Page Number',
        type: 'number',
        required: false,
        description: 'The number of page to be downloaded.',
      },
      {
        name: 'pageSize',
        label: 'Page Size',
        type: 'number',
        required: false,
        description: 'The number of rows on each page (CSV: 1–10,000; gzip: 1–20,000; default 1,000).',
      },
      {
        name: 'outputType',
        label: 'Output Type',
        type: 'string',
        required: false,
        description: 'The output format of the download.',
        enum: ['csv', 'gzip'],
      },
    ],
  },
  {
    id: 'revenue-get-column-list',
    name: 'Get column list',
    description: 'Returns the list of columns for the specified BI view.',
    method: 'GET',
    path: '/api/integration/v2/biviews/{tmpl_name}/describe-columns',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'tmpl_name',
        label: 'Template Name',
        type: 'string',
        required: true,
        description: 'Name of the BI view.',
      },
    ],
  },

  // ── File Upload ───────────────────────────────────────────────────────────
  {
    id: 'revenue-get-file-upload-status',
    name: 'Get file upload status',
    description: 'Returns the status of the specified file upload request.',
    method: 'GET',
    path: '/api/integration/v1/fileupload/status/{file_request_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'file_request_id',
        label: 'File Request ID',
        type: 'number',
        required: true,
        description: 'The request ID of the file upload to be queried.',
      },
    ],
  },
  {
    id: 'revenue-upload-file',
    name: 'Upload file',
    description: 'Uploads a CSV file to Zuora Revenue using multipart/form-data. Set templatename and Content-Type: multipart/form-data as custom headers.',
    method: 'POST',
    path: '/api/integration/v1/upload/file',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    headers: { 'Content-Type': 'multipart/form-data' },
  },

  // ── Inbound ───────────────────────────────────────────────────────────────
  {
    id: 'revenue-get-upload-status',
    name: 'Get upload status',
    description: 'Returns the status of the specified CSV upload request.',
    method: 'GET',
    path: '/api/integration/v1/csv/upload/status',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    queryParams: [
      {
        name: 'id',
        label: 'Request ID',
        type: 'number',
        required: true,
        description: 'The request ID of the uploaded file for which the status is being queried.',
      },
    ],
  },
  {
    id: 'revenue-create-upload',
    name: 'Create upload',
    description: 'Uploads CSV data to Zuora Revenue. Pass templatename and filename as custom headers.',
    method: 'POST',
    path: '/api/integration/v1/csv/upload',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
  },

  // ── Reports ───────────────────────────────────────────────────────────────
  {
    id: 'revenue-get-report-list',
    name: 'Get report list',
    description: 'Returns the list of available reports, optionally filtered by creation date.',
    method: 'GET',
    path: '/api/integration/v1/reports/list',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    queryParams: [
      {
        name: 'createddate',
        label: 'Created Date',
        type: 'string',
        required: false,
        description: 'The date when reports are created.',
        placeholder: 'YYYY-MM-DD',
      },
    ],
  },
  {
    id: 'revenue-download-report',
    name: 'Download a report',
    description: 'Downloads the specified report file.',
    method: 'GET',
    path: '/api/integration/v1/reports/download/{filename}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'filename',
        label: 'Filename',
        type: 'string',
        required: true,
        description: 'The name of the report file to be downloaded.',
      },
    ],
  },
  {
    id: 'revenue-get-report-data',
    name: 'Get report data',
    description: 'Returns a signed URL to download the specified report. Use the report ID from the Get report list response.',
    method: 'GET',
    path: '/api/integration/v2/reports/signedurl/{report_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'report_id',
        label: 'Report ID',
        type: 'number',
        required: true,
        description: 'The ID of the report to be downloaded. Get this from the Get report list response.',
      },
    ],
  },

  // ── Revenue Jobs ──────────────────────────────────────────────────────────
  {
    id: 'revenue-get-programs',
    name: 'Get list of available programs',
    description: 'Returns the list of available programs and their parameters in Zuora Revenue.',
    method: 'GET',
    path: '/api/integration/v1/programs',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
  },
  {
    id: 'revenue-get-revenue-orgs',
    name: 'Get list of available organizations',
    description: 'Returns the list of available organizations in Zuora Revenue.',
    method: 'GET',
    path: '/api/integration/v1/revenue-orgs',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
  },
  {
    id: 'revenue-submit-program',
    name: 'Submit a program',
    description: 'Submits a program with the specified parameters in Zuora Revenue.',
    method: 'POST',
    path: '/api/integration/v1/{orgId}/programs/{programId}/submit',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'orgId',
        label: 'Organization ID',
        type: 'number',
        required: true,
        description: 'The ID of the organization. Get this from the Get list of available organizations response.',
      },
      {
        name: 'programId',
        label: 'Program ID',
        type: 'number',
        required: true,
        description: 'The ID of the program to submit. Get this from the Get list of available programs response.',
      },
    ],
    bodyFields: [
      {
        name: 'parameters',
        label: 'Parameters',
        type: 'array',
        required: false,
        description: 'Array of parameter values for the program.',
        itemFields: [
          {
            name: 'parameter_id',
            label: 'Parameter ID',
            type: 'number',
            required: true,
            description: 'The ID of the parameter.',
            defaultValue: 1002,
          },
          {
            name: 'sequence',
            label: 'Sequence',
            type: 'number',
            required: true,
            description: 'The sequence number of the parameter.',
            defaultValue: 1,
          },
          {
            name: 'parameter_value',
            label: 'Parameter Value',
            type: 'string',
            required: true,
            description: 'The value to use for this parameter.',
          },
        ],
      },
    ],
  },
  {
    id: 'revenue-get-job-status',
    name: 'Get job status',
    description: 'Returns the status of the specified job.',
    method: 'GET',
    path: '/api/integration/v1/{orgId}/jobs/{jobId}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'orgId',
        label: 'Organization ID',
        type: 'number',
        required: true,
        description: 'The ID of the organization that is specified when the job is submitted.',
      },
      {
        name: 'jobId',
        label: 'Job ID',
        type: 'number',
        required: true,
        description: 'The ID of the job.',
      },
    ],
  },

  // ── Stage Error ───────────────────────────────────────────────────────────
  {
    id: 'revenue-get-staging-error',
    name: 'Get staging error',
    description: 'Returns staging errors of the specified error type.',
    method: 'GET',
    path: '/api/integration/v1/stage/error/{errortype}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'errortype',
        label: 'Error Type',
        type: 'string',
        required: true,
        description: 'The type of errors to retrieve.',
      },
    ],
  },

  // ── Transfer Accounting ───────────────────────────────────────────────────
  {
    id: 'revenue-get-transfer-batch-list',
    name: 'Get transfer batch list',
    description: 'Returns the list of all transfer accounting batches.',
    method: 'GET',
    path: '/api/integration/v1/journal/list',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
  },
  {
    id: 'revenue-get-transfer-batch',
    name: 'Get transfer batch',
    description: 'Returns the data for a specific page of the specified transfer accounting batch.',
    method: 'GET',
    path: '/api/integration/v1/journal/batch/{batchid}/{pagenum}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'batchid',
        label: 'Batch ID',
        type: 'number',
        required: true,
        description: 'The batch ID of the transfer accounting batch.',
      },
      {
        name: 'pagenum',
        label: 'Page Number',
        type: 'number',
        required: true,
        description: 'The number of the page to be downloaded.',
      },
    ],
    queryParams: [
      {
        name: 'pagesize',
        label: 'Page Size',
        type: 'number',
        required: false,
        description: 'The number of records per request. Default is 1000, maximum is 10000.',
      },
    ],
  },
  {
    id: 'revenue-update-transfer-batch-status',
    name: 'Update transfer batch status',
    description: 'Updates the status of the specified transfer accounting batch.',
    method: 'PUT',
    path: '/api/integration/v1/journal/batch/status/{batch_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'batch_id',
        label: 'Batch ID',
        type: 'number',
        required: true,
        description: 'The batch ID of the transfer accounting batch.',
      },
    ],
  },

  // ── Transfer Accounting Files ─────────────────────────────────────────────
  {
    id: 'revenue-get-transfer-batch-file',
    name: 'Get transfer batch file',
    description: 'Downloads the file for the specified transfer accounting batch.',
    method: 'GET',
    path: '/api/integration/v1/download/transferbatchfile/{batch_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'batch_id',
        label: 'Batch ID',
        type: 'number',
        required: true,
        description: 'The batch ID of the transfer accounting batch.',
      },
    ],
  },

  // ── Data Collection ───────────────────────────────────────────────────────
  {
    id: 'revenue-submit-data-collection-job',
    name: 'Submit data collection job',
    description: 'Submits a data collection job using the specified RC grouping template.',
    method: 'POST',
    path: '/api/integration/v1/job/collection/template',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    headers: { 'Content-Type': 'application/json' },
    bodyFields: [
      {
        name: 'rc_template_name',
        label: 'RC Template Name',
        type: 'string',
        required: true,
        description: 'Name of the RC template defined in Zuora Revenue (Policies > RC Grouping Template).',
      },
      {
        name: 'org_id',
        label: 'Organization ID',
        type: 'number',
        required: false,
        description: 'The organization ID (Setups > Application > Organization). Required only for multi-organization tenants.',
        defaultValue: 0,
      },
    ],
  },
  {
    id: 'revenue-get-data-collection-job',
    name: 'Get data collection job details',
    description: 'Returns the details and status of the specified data collection job.',
    method: 'GET',
    path: '/api/integration/v1/job/collection/template/{job_id}',
    baseUrl: REVENUE_BASE,
    requiresAuth: true,
    authType: 'revenue-token',
    product: 'revenue',
    pathParams: [
      {
        name: 'job_id',
        label: 'Job ID',
        type: 'number',
        required: true,
        description: 'The ID of the data collection job returned when the job was submitted.',
      },
    ],
  },
];

export const REVENUE_CATEGORIES = [
  { id: 'revenue-adapter', label: 'Adapter', tag: 'Adapter' },
  { id: 'revenue-bi-views-v1', label: 'BI Views v1', tag: 'BI Views v1' },
  { id: 'revenue-bi-views-v2', label: 'BI Views v2', tag: 'BI Views v2' },
  { id: 'revenue-file-upload', label: 'File Upload', tag: 'File Upload' },
  { id: 'revenue-inbound', label: 'Inbound', tag: 'Inbound' },
  { id: 'revenue-reports', label: 'Reports', tag: 'Reports' },
  { id: 'revenue-jobs', label: 'Revenue Jobs', tag: 'Revenue Jobs' },
  { id: 'revenue-stage-error', label: 'Stage Error', tag: 'Stage Error' },
  { id: 'revenue-transfer-accounting', label: 'Transfer Accounting', tag: 'Transfer Accounting' },
  { id: 'revenue-transfer-accounting-files', label: 'Transfer Accounting Files', tag: 'Transfer Accounting Files' },
  { id: 'revenue-data-collection', label: 'Data Collection', tag: 'Data Collection' },
] as const;

const tagMap: Record<string, string[]> = {
  'revenue-adapter': ['revenue-get-field-mapping'],
  'revenue-bi-views-v1': ['revenue-get-bi-views', 'revenue-get-bi-view-data-selected-fields'],
  'revenue-bi-views-v2': ['revenue-get-all-task-status', 'revenue-cancel-task', 'revenue-get-active-task-details', 'revenue-get-row-count', 'revenue-download-bi-view', 'revenue-get-column-list'],
  'revenue-file-upload': ['revenue-get-file-upload-status', 'revenue-upload-file'],
  'revenue-inbound': ['revenue-get-upload-status', 'revenue-create-upload'],
  'revenue-reports': ['revenue-get-report-list', 'revenue-download-report', 'revenue-get-report-data'],
  'revenue-jobs': ['revenue-get-programs', 'revenue-get-revenue-orgs', 'revenue-submit-program', 'revenue-get-job-status'],
  'revenue-stage-error': ['revenue-get-staging-error'],
  'revenue-transfer-accounting': ['revenue-get-transfer-batch-list', 'revenue-get-transfer-batch', 'revenue-update-transfer-batch-status'],
  'revenue-transfer-accounting-files': ['revenue-get-transfer-batch-file'],
  'revenue-data-collection': ['revenue-submit-data-collection-job', 'revenue-get-data-collection-job'],
};

export const getRevenueCategoryEndpoints = (categoryId: string): ApiEndpoint[] => {
  const ids = tagMap[categoryId] ?? [];
  return revenueEndpoints.filter((e) => ids.includes(e.id));
};
